baseURL = 'https://bayborodin.ru/'
languageCode = 'ru-ru'
googleAnalytics = 'G-LCRMSXX49D'
title = 'Лабораторный журнал'
theme =  ["github.com/Mitrichius/hugo-theme-anubis"]
[params]
  author = 'Николай Байбородин'
  readMore = true
[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true